spring.application.name=oauth2

server.port=4200
spring.datasource.url=jdbc:h2:file:~/Desktop/oauth2Db;AUTO_SERVER=TRUE
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://127.0.0.1:4200
# spring.security.oauth2.client.registration=