spring.application.name=oauth2

server.port=4200
spring.datasource.url=jdbc:h2:file:~/Desktop/oauth2Db;AUTO_SERVER=TRUE
spring.sql.init.mode=always
spring.h2.console.enabled=true
spring.jpa.defer-datasource-initialization=true
